# Generated by Django 2.2.2 on 2019-06-20 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output', models.TextField(blank=True, default='', verbose_name='Result of the utility running')),
                ('ready', models.BooleanField(default=False, verbose_name='Flag for the utility readiness (False - running, True - done)')),
                ('exitcode', models.IntegerField(default=None, null=True, verbose_name='Exit code of utility process')),
            ],
        ),
    ]
